# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: |
          ${{github.workspace}}/server/package-lock.json
          ${{github.workspace}}/client/package-lock.json
    - run: npm ci
      working-directory: ${{github.workspace}}/server
    - run: npm run build --if-present
      working-directory: ${{github.workspace}}/server
    - run: npm install
      working-directory: ${{github.workspace}}/client
    - run: npm run build --if-present
      working-directory: ${{github.workspace}}/client
    #- run: npm ci
     # working-directory: ${{github.workspace}}/client
    #- run: npm run build --if-present
    #- run: npm build
    #  working-directory: ${{github.workspace}}/client
    #- run: npm test // unit tests have not been implemented into our package.json
